### ISSUE TITLE
少了排行的功能

### ISSUE THREAD

**Issue by puff-tw** [AnNOtis/PixelShowWebSite#10]
少了排行的功能，目前只有 全部、今日、週、月 的找找看。
透過 排行的功能  針對 加入最愛 做排序， 便可方便知道 用戶 偏好，也能調查出 特定族群( 某些Tag ) 的偏好。

**Comment by AnNOtis** [comment]
這在開發計畫中，感謝回饋 :+1:

**Comment by AnNOtis** [comment]
merge to #14
