### ISSUE TITLE
作品的 Facebook Share 無法秀出作品圖片

### ISSUE THREAD

**Issue by puff-tw** [AnNOtis/PixelShowWebSite#13]
作品的 Facebook Share 無法秀出作品圖片
這樣就失去讓人想點進去的目的。

如下圖
![fb_share](https://cloud.githubusercontent.com/assets/6845820/5868959/7a129310-a2ec-11e4-8c42-d4a14d61b5a3.png)

**Comment by AnNOtis** [comment]
closed by 433e137
